
LIBRARIES = [
	"Game Assets"
]

SCREENSHOT_PATH = "SCREENSHOTS"

LAUNCHER_BLEND = "Launcher"
KEYMAP_BLEND = "Keymap"

LIBLOAD_TYPE = "NORMAL" #"ASYNC" or "NORMAL"
DO_STABILITY = True
LOW_CLIP = -1000

DEFAULT_PLAYER = "Actor"
