
LIBRARIES = []

SCREENSHOT_PATH = "SCREENSHOTS"
LIBRARY_PATH = ""

LAUNCHER_BLEND = "Launcher"
KEYMAP_BLEND = "Keymap"

LIBLOAD_TYPE = "NORMAL" #"ASYNC" or "NORMAL"
DO_STABILITY = True
LOW_CLIP = -1000
CAMERA_CLIP = [0.1, 20000]
MOUSE_BUFFER = True

DEFAULT_PLAYER = "CorePlayer"
